name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Ruff linter
        run: uv run ruff check --output-format=github .

      - name: Run Ruff formatter check
        run: uv run ruff format --check .
